// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuditLogInitParameters struct {

	// (Number) To configure how long audit logs should be kept. For example, if you set this to 24 Harbor will only purge audit logs that are 24 or more hours old.
	AuditRetentionHour *int64 `json:"auditRetentionHour,omitempty" tf:"audit_retention_hour,omitempty"`

	// (String) Valid values are create, push, pull, delete, create_artifact, delete_artifact, pull_artifact, other, those values can be comma separated. Harbor will include audit logs for those events in the purge (minimal version Harbor 2.13).
	IncludeEventTypes *string `json:"includeEventTypes,omitempty" tf:"include_event_types,omitempty"`

	// (String) Valid values are create, delete, pull, those values can be comma separated. When Create, Delete, or Pull is set, Harbor will include audit logs for those operations in the purge. (Harbor < 2.13, deprecated in favor of include_event_types)
	IncludeOperations *string `json:"includeOperations,omitempty" tf:"include_operations,omitempty"`

	// (String) Sets the schedule how often the Garbage Collection will run.  Can be to "Hourly", "Daily", "Weekly" or can be a custom cron string ie, "5 4 * * *"
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type AuditLogObservation struct {

	// (Number) To configure how long audit logs should be kept. For example, if you set this to 24 Harbor will only purge audit logs that are 24 or more hours old.
	AuditRetentionHour *int64 `json:"auditRetentionHour,omitempty" tf:"audit_retention_hour,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Valid values are create, push, pull, delete, create_artifact, delete_artifact, pull_artifact, other, those values can be comma separated. Harbor will include audit logs for those events in the purge (minimal version Harbor 2.13).
	IncludeEventTypes *string `json:"includeEventTypes,omitempty" tf:"include_event_types,omitempty"`

	// (String) Valid values are create, delete, pull, those values can be comma separated. When Create, Delete, or Pull is set, Harbor will include audit logs for those operations in the purge. (Harbor < 2.13, deprecated in favor of include_event_types)
	IncludeOperations *string `json:"includeOperations,omitempty" tf:"include_operations,omitempty"`

	// (String) Sets the schedule how often the Garbage Collection will run.  Can be to "Hourly", "Daily", "Weekly" or can be a custom cron string ie, "5 4 * * *"
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type AuditLogParameters struct {

	// (Number) To configure how long audit logs should be kept. For example, if you set this to 24 Harbor will only purge audit logs that are 24 or more hours old.
	// +kubebuilder:validation:Optional
	AuditRetentionHour *int64 `json:"auditRetentionHour,omitempty" tf:"audit_retention_hour,omitempty"`

	// (String) Valid values are create, push, pull, delete, create_artifact, delete_artifact, pull_artifact, other, those values can be comma separated. Harbor will include audit logs for those events in the purge (minimal version Harbor 2.13).
	// +kubebuilder:validation:Optional
	IncludeEventTypes *string `json:"includeEventTypes,omitempty" tf:"include_event_types,omitempty"`

	// (String) Valid values are create, delete, pull, those values can be comma separated. When Create, Delete, or Pull is set, Harbor will include audit logs for those operations in the purge. (Harbor < 2.13, deprecated in favor of include_event_types)
	// +kubebuilder:validation:Optional
	IncludeOperations *string `json:"includeOperations,omitempty" tf:"include_operations,omitempty"`

	// (String) Sets the schedule how often the Garbage Collection will run.  Can be to "Hourly", "Daily", "Weekly" or can be a custom cron string ie, "5 4 * * *"
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

// AuditLogSpec defines the desired state of AuditLog
type AuditLogSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AuditLogParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuditLogInitParameters `json:"initProvider,omitempty"`
}

// AuditLogStatus defines the observed state of AuditLog.
type AuditLogStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuditLogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AuditLog is the Schema for the AuditLogs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harbor}
type AuditLog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.auditRetentionHour) || (has(self.initProvider) && has(self.initProvider.auditRetentionHour))",message="spec.forProvider.auditRetentionHour is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schedule) || (has(self.initProvider) && has(self.initProvider.schedule))",message="spec.forProvider.schedule is a required parameter"
	Spec   AuditLogSpec   `json:"spec"`
	Status AuditLogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuditLogList contains a list of AuditLogs
type AuditLogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuditLog `json:"items"`
}

// Repository type metadata.
var (
	AuditLog_Kind             = "AuditLog"
	AuditLog_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuditLog_Kind}.String()
	AuditLog_KindAPIVersion   = AuditLog_Kind + "." + CRDGroupVersion.String()
	AuditLog_GroupVersionKind = CRDGroupVersion.WithKind(AuditLog_Kind)
)

func init() {
	SchemeBuilder.Register(&AuditLog{}, &AuditLogList{})
}
