apiVersion: retention.harbor.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: retention/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: crossplane-system
spec:
  forProvider:
    rule:
    - nDaysSinceLastPull: 5
      repoMatching: '**'
      tagMatching: latest
    - nDaysSinceLastPush: 10
      repoMatching: '**'
      tagMatching: '{latest,snapshot}'
    schedule: Daily
    scopeSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: harbor.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: retention/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: crossplane-system
spec:
  forProvider: {}
