// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PolicyInitParameters struct {

	// (Block List, Min: 1, Max: 15) (see below for nested schema)
	Rule []RuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// (String) The schedule of when you would like the policy to run. This can be Hourly, Daily, Weekly or can be a custom cron string.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (String) The project id of which you would like to apply this policy.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type PolicyObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block List, Min: 1, Max: 15) (see below for nested schema)
	Rule []RuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// (String) The schedule of when you would like the policy to run. This can be Hourly, Daily, Weekly or can be a custom cron string.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (String) The project id of which you would like to apply this policy.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type PolicyParameters struct {

	// (Block List, Min: 1, Max: 15) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rule []RuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// (String) The schedule of when you would like the policy to run. This can be Hourly, Daily, Weekly or can be a custom cron string.
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (String) The project id of which you would like to apply this policy.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type RuleInitParameters struct {

	// (Boolean) retain always.
	AlwaysRetain *bool `json:"alwaysRetain,omitempty" tf:"always_retain,omitempty"`

	// (Boolean) Specify if the rule is disable or not. Defaults to false
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Number) retain the most recently pulled n artifacts.
	MostRecentlyPulled *int64 `json:"mostRecentlyPulled,omitempty" tf:"most_recently_pulled,omitempty"`

	// (Number) retain the most recently pushed n artifacts.
	MostRecentlyPushed *int64 `json:"mostRecentlyPushed,omitempty" tf:"most_recently_pushed,omitempty"`

	// (Number) retains the artifacts pulled within the lasts n days.
	NDaysSinceLastPull *int64 `json:"nDaysSinceLastPull,omitempty" tf:"n_days_since_last_pull,omitempty"`

	// (Number) retains the artifacts pushed within the lasts n days.
	NDaysSinceLastPush *int64 `json:"nDaysSinceLastPush,omitempty" tf:"n_days_since_last_push,omitempty"`

	// (String) For the repositories excluding.
	RepoExcluding *string `json:"repoExcluding,omitempty" tf:"repo_excluding,omitempty"`

	// (String) For the repositories matching.
	RepoMatching *string `json:"repoMatching,omitempty" tf:"repo_matching,omitempty"`

	// (String) For the tag excluding.
	TagExcluding *string `json:"tagExcluding,omitempty" tf:"tag_excluding,omitempty"`

	// (String) For the tag matching.
	TagMatching *string `json:"tagMatching,omitempty" tf:"tag_matching,omitempty"`

	// (Boolean) with untagged artifacts. Defaults to true
	UntaggedArtifacts *bool `json:"untaggedArtifacts,omitempty" tf:"untagged_artifacts,omitempty"`
}

type RuleObservation struct {

	// (Boolean) retain always.
	AlwaysRetain *bool `json:"alwaysRetain,omitempty" tf:"always_retain,omitempty"`

	// (Boolean) Specify if the rule is disable or not. Defaults to false
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Number) retain the most recently pulled n artifacts.
	MostRecentlyPulled *int64 `json:"mostRecentlyPulled,omitempty" tf:"most_recently_pulled,omitempty"`

	// (Number) retain the most recently pushed n artifacts.
	MostRecentlyPushed *int64 `json:"mostRecentlyPushed,omitempty" tf:"most_recently_pushed,omitempty"`

	// (Number) retains the artifacts pulled within the lasts n days.
	NDaysSinceLastPull *int64 `json:"nDaysSinceLastPull,omitempty" tf:"n_days_since_last_pull,omitempty"`

	// (Number) retains the artifacts pushed within the lasts n days.
	NDaysSinceLastPush *int64 `json:"nDaysSinceLastPush,omitempty" tf:"n_days_since_last_push,omitempty"`

	// (String) For the repositories excluding.
	RepoExcluding *string `json:"repoExcluding,omitempty" tf:"repo_excluding,omitempty"`

	// (String) For the repositories matching.
	RepoMatching *string `json:"repoMatching,omitempty" tf:"repo_matching,omitempty"`

	// (String) For the tag excluding.
	TagExcluding *string `json:"tagExcluding,omitempty" tf:"tag_excluding,omitempty"`

	// (String) For the tag matching.
	TagMatching *string `json:"tagMatching,omitempty" tf:"tag_matching,omitempty"`

	// (Boolean) with untagged artifacts. Defaults to true
	UntaggedArtifacts *bool `json:"untaggedArtifacts,omitempty" tf:"untagged_artifacts,omitempty"`
}

type RuleParameters struct {

	// (Boolean) retain always.
	// +kubebuilder:validation:Optional
	AlwaysRetain *bool `json:"alwaysRetain,omitempty" tf:"always_retain,omitempty"`

	// (Boolean) Specify if the rule is disable or not. Defaults to false
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Number) retain the most recently pulled n artifacts.
	// +kubebuilder:validation:Optional
	MostRecentlyPulled *int64 `json:"mostRecentlyPulled,omitempty" tf:"most_recently_pulled,omitempty"`

	// (Number) retain the most recently pushed n artifacts.
	// +kubebuilder:validation:Optional
	MostRecentlyPushed *int64 `json:"mostRecentlyPushed,omitempty" tf:"most_recently_pushed,omitempty"`

	// (Number) retains the artifacts pulled within the lasts n days.
	// +kubebuilder:validation:Optional
	NDaysSinceLastPull *int64 `json:"nDaysSinceLastPull,omitempty" tf:"n_days_since_last_pull,omitempty"`

	// (Number) retains the artifacts pushed within the lasts n days.
	// +kubebuilder:validation:Optional
	NDaysSinceLastPush *int64 `json:"nDaysSinceLastPush,omitempty" tf:"n_days_since_last_push,omitempty"`

	// (String) For the repositories excluding.
	// +kubebuilder:validation:Optional
	RepoExcluding *string `json:"repoExcluding,omitempty" tf:"repo_excluding,omitempty"`

	// (String) For the repositories matching.
	// +kubebuilder:validation:Optional
	RepoMatching *string `json:"repoMatching,omitempty" tf:"repo_matching,omitempty"`

	// (String) For the tag excluding.
	// +kubebuilder:validation:Optional
	TagExcluding *string `json:"tagExcluding,omitempty" tf:"tag_excluding,omitempty"`

	// (String) For the tag matching.
	// +kubebuilder:validation:Optional
	TagMatching *string `json:"tagMatching,omitempty" tf:"tag_matching,omitempty"`

	// (Boolean) with untagged artifacts. Defaults to true
	// +kubebuilder:validation:Optional
	UntaggedArtifacts *bool `json:"untaggedArtifacts,omitempty" tf:"untagged_artifacts,omitempty"`
}

// PolicySpec defines the desired state of Policy
type PolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatus defines the observed state of Policy.
type PolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Policy is the Schema for the Policys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harbor}
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || (has(self.initProvider) && has(self.initProvider.rule))",message="spec.forProvider.rule is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scope) || (has(self.initProvider) && has(self.initProvider.scope))",message="spec.forProvider.scope is a required parameter"
	Spec   PolicySpec   `json:"spec"`
	Status PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyList contains a list of Policys
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

// Repository type metadata.
var (
	Policy_Kind             = "Policy"
	Policy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Policy_Kind}.String()
	Policy_KindAPIVersion   = Policy_Kind + "." + CRDGroupVersion.String()
	Policy_GroupVersionKind = CRDGroupVersion.WithKind(Policy_Kind)
)

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
