apiVersion: harbor.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: harbor/v1alpha1/group
  labels:
    testing.upbound.io/example-name: storage-group
  name: storage-group
  namespace: crossplane-system
spec:
  forProvider:
    groupName: storage-group
    groupType: 2
