apiVersion: config.harbor.m.crossplane.io/v1alpha1
kind: Auth
metadata:
  annotations:
    meta.upbound.io/example-id: config/v1alpha1/auth
  labels:
    testing.upbound.io/example-name: oidc
  name: oidc
  namespace: crossplane-system
spec:
  forProvider:
    authMode: oidc_auth
    oidcAdminGroup: administrators
    oidcAutoOnboard: true
    oidcClientId: OIDC Client ID goes here
    oidcClientSecretSecretRef:
      key: example-key
      name: example-secret
    oidcEndpoint: https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0
    oidcName: azure
    oidcScope: openid,email
    oidcUserClaim: name
    oidcVerifyCert: true
    primaryAuthMode: true

---

apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: config/v1alpha1/auth
  labels:
    testing.upbound.io/example-name: main
  name: example-secret
  namespace: crossplane-system
stringData:
  example-key: "client-secret"
type: Opaque
