//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Auth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthInitParameters) DeepCopyInto(out *AuthInitParameters) {
	*out = *in
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.LdapBaseDn != nil {
		in, out := &in.LdapBaseDn, &out.LdapBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapFilter != nil {
		in, out := &in.LdapFilter, &out.LdapFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupAdminDn != nil {
		in, out := &in.LdapGroupAdminDn, &out.LdapGroupAdminDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupBaseDn != nil {
		in, out := &in.LdapGroupBaseDn, &out.LdapGroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupFilter != nil {
		in, out := &in.LdapGroupFilter, &out.LdapGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupGID != nil {
		in, out := &in.LdapGroupGID, &out.LdapGroupGID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupMembership != nil {
		in, out := &in.LdapGroupMembership, &out.LdapGroupMembership
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupScope != nil {
		in, out := &in.LdapGroupScope, &out.LdapGroupScope
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupUID != nil {
		in, out := &in.LdapGroupUID, &out.LdapGroupUID
		*out = new(string)
		**out = **in
	}
	if in.LdapScope != nil {
		in, out := &in.LdapScope, &out.LdapScope
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchDn != nil {
		in, out := &in.LdapSearchDn, &out.LdapSearchDn
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchPasswordSecretRef != nil {
		in, out := &in.LdapSearchPasswordSecretRef, &out.LdapSearchPasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.LdapUID != nil {
		in, out := &in.LdapUID, &out.LdapUID
		*out = new(string)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.LdapVerifyCert != nil {
		in, out := &in.LdapVerifyCert, &out.LdapVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.OidcAdminGroup != nil {
		in, out := &in.OidcAdminGroup, &out.OidcAdminGroup
		*out = new(string)
		**out = **in
	}
	if in.OidcAutoOnboard != nil {
		in, out := &in.OidcAutoOnboard, &out.OidcAutoOnboard
		*out = new(bool)
		**out = **in
	}
	if in.OidcClientID != nil {
		in, out := &in.OidcClientID, &out.OidcClientID
		*out = new(string)
		**out = **in
	}
	if in.OidcClientSecretSecretRef != nil {
		in, out := &in.OidcClientSecretSecretRef, &out.OidcClientSecretSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.OidcEndpoint != nil {
		in, out := &in.OidcEndpoint, &out.OidcEndpoint
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupFilter != nil {
		in, out := &in.OidcGroupFilter, &out.OidcGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupsClaim != nil {
		in, out := &in.OidcGroupsClaim, &out.OidcGroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcLogout != nil {
		in, out := &in.OidcLogout, &out.OidcLogout
		*out = new(bool)
		**out = **in
	}
	if in.OidcName != nil {
		in, out := &in.OidcName, &out.OidcName
		*out = new(string)
		**out = **in
	}
	if in.OidcScope != nil {
		in, out := &in.OidcScope, &out.OidcScope
		*out = new(string)
		**out = **in
	}
	if in.OidcUserClaim != nil {
		in, out := &in.OidcUserClaim, &out.OidcUserClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcVerifyCert != nil {
		in, out := &in.OidcVerifyCert, &out.OidcVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryAuthMode != nil {
		in, out := &in.PrimaryAuthMode, &out.PrimaryAuthMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthInitParameters.
func (in *AuthInitParameters) DeepCopy() *AuthInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthList) DeepCopyInto(out *AuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Auth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthList.
func (in *AuthList) DeepCopy() *AuthList {
	if in == nil {
		return nil
	}
	out := new(AuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthObservation) DeepCopyInto(out *AuthObservation) {
	*out = *in
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LdapBaseDn != nil {
		in, out := &in.LdapBaseDn, &out.LdapBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapFilter != nil {
		in, out := &in.LdapFilter, &out.LdapFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupAdminDn != nil {
		in, out := &in.LdapGroupAdminDn, &out.LdapGroupAdminDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupBaseDn != nil {
		in, out := &in.LdapGroupBaseDn, &out.LdapGroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupFilter != nil {
		in, out := &in.LdapGroupFilter, &out.LdapGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupGID != nil {
		in, out := &in.LdapGroupGID, &out.LdapGroupGID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupMembership != nil {
		in, out := &in.LdapGroupMembership, &out.LdapGroupMembership
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupScope != nil {
		in, out := &in.LdapGroupScope, &out.LdapGroupScope
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupUID != nil {
		in, out := &in.LdapGroupUID, &out.LdapGroupUID
		*out = new(string)
		**out = **in
	}
	if in.LdapScope != nil {
		in, out := &in.LdapScope, &out.LdapScope
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchDn != nil {
		in, out := &in.LdapSearchDn, &out.LdapSearchDn
		*out = new(string)
		**out = **in
	}
	if in.LdapUID != nil {
		in, out := &in.LdapUID, &out.LdapUID
		*out = new(string)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.LdapVerifyCert != nil {
		in, out := &in.LdapVerifyCert, &out.LdapVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.OidcAdminGroup != nil {
		in, out := &in.OidcAdminGroup, &out.OidcAdminGroup
		*out = new(string)
		**out = **in
	}
	if in.OidcAutoOnboard != nil {
		in, out := &in.OidcAutoOnboard, &out.OidcAutoOnboard
		*out = new(bool)
		**out = **in
	}
	if in.OidcClientID != nil {
		in, out := &in.OidcClientID, &out.OidcClientID
		*out = new(string)
		**out = **in
	}
	if in.OidcEndpoint != nil {
		in, out := &in.OidcEndpoint, &out.OidcEndpoint
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupFilter != nil {
		in, out := &in.OidcGroupFilter, &out.OidcGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupsClaim != nil {
		in, out := &in.OidcGroupsClaim, &out.OidcGroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcLogout != nil {
		in, out := &in.OidcLogout, &out.OidcLogout
		*out = new(bool)
		**out = **in
	}
	if in.OidcName != nil {
		in, out := &in.OidcName, &out.OidcName
		*out = new(string)
		**out = **in
	}
	if in.OidcScope != nil {
		in, out := &in.OidcScope, &out.OidcScope
		*out = new(string)
		**out = **in
	}
	if in.OidcUserClaim != nil {
		in, out := &in.OidcUserClaim, &out.OidcUserClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcVerifyCert != nil {
		in, out := &in.OidcVerifyCert, &out.OidcVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryAuthMode != nil {
		in, out := &in.PrimaryAuthMode, &out.PrimaryAuthMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthObservation.
func (in *AuthObservation) DeepCopy() *AuthObservation {
	if in == nil {
		return nil
	}
	out := new(AuthObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthParameters) DeepCopyInto(out *AuthParameters) {
	*out = *in
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.LdapBaseDn != nil {
		in, out := &in.LdapBaseDn, &out.LdapBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapFilter != nil {
		in, out := &in.LdapFilter, &out.LdapFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupAdminDn != nil {
		in, out := &in.LdapGroupAdminDn, &out.LdapGroupAdminDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupBaseDn != nil {
		in, out := &in.LdapGroupBaseDn, &out.LdapGroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupFilter != nil {
		in, out := &in.LdapGroupFilter, &out.LdapGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupGID != nil {
		in, out := &in.LdapGroupGID, &out.LdapGroupGID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupMembership != nil {
		in, out := &in.LdapGroupMembership, &out.LdapGroupMembership
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupScope != nil {
		in, out := &in.LdapGroupScope, &out.LdapGroupScope
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupUID != nil {
		in, out := &in.LdapGroupUID, &out.LdapGroupUID
		*out = new(string)
		**out = **in
	}
	if in.LdapScope != nil {
		in, out := &in.LdapScope, &out.LdapScope
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchDn != nil {
		in, out := &in.LdapSearchDn, &out.LdapSearchDn
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchPasswordSecretRef != nil {
		in, out := &in.LdapSearchPasswordSecretRef, &out.LdapSearchPasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.LdapUID != nil {
		in, out := &in.LdapUID, &out.LdapUID
		*out = new(string)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.LdapVerifyCert != nil {
		in, out := &in.LdapVerifyCert, &out.LdapVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.OidcAdminGroup != nil {
		in, out := &in.OidcAdminGroup, &out.OidcAdminGroup
		*out = new(string)
		**out = **in
	}
	if in.OidcAutoOnboard != nil {
		in, out := &in.OidcAutoOnboard, &out.OidcAutoOnboard
		*out = new(bool)
		**out = **in
	}
	if in.OidcClientID != nil {
		in, out := &in.OidcClientID, &out.OidcClientID
		*out = new(string)
		**out = **in
	}
	if in.OidcClientSecretSecretRef != nil {
		in, out := &in.OidcClientSecretSecretRef, &out.OidcClientSecretSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.OidcEndpoint != nil {
		in, out := &in.OidcEndpoint, &out.OidcEndpoint
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupFilter != nil {
		in, out := &in.OidcGroupFilter, &out.OidcGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupsClaim != nil {
		in, out := &in.OidcGroupsClaim, &out.OidcGroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcLogout != nil {
		in, out := &in.OidcLogout, &out.OidcLogout
		*out = new(bool)
		**out = **in
	}
	if in.OidcName != nil {
		in, out := &in.OidcName, &out.OidcName
		*out = new(string)
		**out = **in
	}
	if in.OidcScope != nil {
		in, out := &in.OidcScope, &out.OidcScope
		*out = new(string)
		**out = **in
	}
	if in.OidcUserClaim != nil {
		in, out := &in.OidcUserClaim, &out.OidcUserClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcVerifyCert != nil {
		in, out := &in.OidcVerifyCert, &out.OidcVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryAuthMode != nil {
		in, out := &in.PrimaryAuthMode, &out.PrimaryAuthMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthParameters.
func (in *AuthParameters) DeepCopy() *AuthParameters {
	if in == nil {
		return nil
	}
	out := new(AuthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthStatus) DeepCopyInto(out *AuthStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthStatus.
func (in *AuthStatus) DeepCopy() *AuthStatus {
	if in == nil {
		return nil
	}
	out := new(AuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BannerMessageInitParameters) DeepCopyInto(out *BannerMessageInitParameters) {
	*out = *in
	if in.Closable != nil {
		in, out := &in.Closable, &out.Closable
		*out = new(bool)
		**out = **in
	}
	if in.FromDate != nil {
		in, out := &in.FromDate, &out.FromDate
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ToDate != nil {
		in, out := &in.ToDate, &out.ToDate
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BannerMessageInitParameters.
func (in *BannerMessageInitParameters) DeepCopy() *BannerMessageInitParameters {
	if in == nil {
		return nil
	}
	out := new(BannerMessageInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BannerMessageObservation) DeepCopyInto(out *BannerMessageObservation) {
	*out = *in
	if in.Closable != nil {
		in, out := &in.Closable, &out.Closable
		*out = new(bool)
		**out = **in
	}
	if in.FromDate != nil {
		in, out := &in.FromDate, &out.FromDate
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ToDate != nil {
		in, out := &in.ToDate, &out.ToDate
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BannerMessageObservation.
func (in *BannerMessageObservation) DeepCopy() *BannerMessageObservation {
	if in == nil {
		return nil
	}
	out := new(BannerMessageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BannerMessageParameters) DeepCopyInto(out *BannerMessageParameters) {
	*out = *in
	if in.Closable != nil {
		in, out := &in.Closable, &out.Closable
		*out = new(bool)
		**out = **in
	}
	if in.FromDate != nil {
		in, out := &in.FromDate, &out.FromDate
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ToDate != nil {
		in, out := &in.ToDate, &out.ToDate
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BannerMessageParameters.
func (in *BannerMessageParameters) DeepCopy() *BannerMessageParameters {
	if in == nil {
		return nil
	}
	out := new(BannerMessageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Security) DeepCopyInto(out *Security) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Security.
func (in *Security) DeepCopy() *Security {
	if in == nil {
		return nil
	}
	out := new(Security)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Security) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityInitParameters) DeepCopyInto(out *SecurityInitParameters) {
	*out = *in
	if in.CveAllowlist != nil {
		in, out := &in.CveAllowlist, &out.CveAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityInitParameters.
func (in *SecurityInitParameters) DeepCopy() *SecurityInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecurityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityList) DeepCopyInto(out *SecurityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Security, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityList.
func (in *SecurityList) DeepCopy() *SecurityList {
	if in == nil {
		return nil
	}
	out := new(SecurityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityObservation) DeepCopyInto(out *SecurityObservation) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.CveAllowlist != nil {
		in, out := &in.CveAllowlist, &out.CveAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityObservation.
func (in *SecurityObservation) DeepCopy() *SecurityObservation {
	if in == nil {
		return nil
	}
	out := new(SecurityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityParameters) DeepCopyInto(out *SecurityParameters) {
	*out = *in
	if in.CveAllowlist != nil {
		in, out := &in.CveAllowlist, &out.CveAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityParameters.
func (in *SecurityParameters) DeepCopy() *SecurityParameters {
	if in == nil {
		return nil
	}
	out := new(SecurityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityStatus) DeepCopyInto(out *SecurityStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityStatus.
func (in *SecurityStatus) DeepCopy() *SecurityStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *System) DeepCopyInto(out *System) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new System.
func (in *System) DeepCopy() *System {
	if in == nil {
		return nil
	}
	out := new(System)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *System) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInitParameters) DeepCopyInto(out *SystemInitParameters) {
	*out = *in
	if in.AuditLogForwardEndpoint != nil {
		in, out := &in.AuditLogForwardEndpoint, &out.AuditLogForwardEndpoint
		*out = new(string)
		**out = **in
	}
	if in.BannerMessage != nil {
		in, out := &in.BannerMessage, &out.BannerMessage
		*out = make([]BannerMessageInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationEnable != nil {
		in, out := &in.NotificationEnable, &out.NotificationEnable
		*out = new(bool)
		**out = **in
	}
	if in.ProjectCreationRestriction != nil {
		in, out := &in.ProjectCreationRestriction, &out.ProjectCreationRestriction
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.RobotNamePrefix != nil {
		in, out := &in.RobotNamePrefix, &out.RobotNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.RobotTokenExpiration != nil {
		in, out := &in.RobotTokenExpiration, &out.RobotTokenExpiration
		*out = new(float64)
		**out = **in
	}
	if in.ScannerSkipUpdatePulltime != nil {
		in, out := &in.ScannerSkipUpdatePulltime, &out.ScannerSkipUpdatePulltime
		*out = new(bool)
		**out = **in
	}
	if in.SkipAuditLogDatabase != nil {
		in, out := &in.SkipAuditLogDatabase, &out.SkipAuditLogDatabase
		*out = new(bool)
		**out = **in
	}
	if in.StoragePerProject != nil {
		in, out := &in.StoragePerProject, &out.StoragePerProject
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInitParameters.
func (in *SystemInitParameters) DeepCopy() *SystemInitParameters {
	if in == nil {
		return nil
	}
	out := new(SystemInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemList) DeepCopyInto(out *SystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]System, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemList.
func (in *SystemList) DeepCopy() *SystemList {
	if in == nil {
		return nil
	}
	out := new(SystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemObservation) DeepCopyInto(out *SystemObservation) {
	*out = *in
	if in.AuditLogForwardEndpoint != nil {
		in, out := &in.AuditLogForwardEndpoint, &out.AuditLogForwardEndpoint
		*out = new(string)
		**out = **in
	}
	if in.BannerMessage != nil {
		in, out := &in.BannerMessage, &out.BannerMessage
		*out = make([]BannerMessageObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NotificationEnable != nil {
		in, out := &in.NotificationEnable, &out.NotificationEnable
		*out = new(bool)
		**out = **in
	}
	if in.ProjectCreationRestriction != nil {
		in, out := &in.ProjectCreationRestriction, &out.ProjectCreationRestriction
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.RobotNamePrefix != nil {
		in, out := &in.RobotNamePrefix, &out.RobotNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.RobotTokenExpiration != nil {
		in, out := &in.RobotTokenExpiration, &out.RobotTokenExpiration
		*out = new(float64)
		**out = **in
	}
	if in.ScannerSkipUpdatePulltime != nil {
		in, out := &in.ScannerSkipUpdatePulltime, &out.ScannerSkipUpdatePulltime
		*out = new(bool)
		**out = **in
	}
	if in.SkipAuditLogDatabase != nil {
		in, out := &in.SkipAuditLogDatabase, &out.SkipAuditLogDatabase
		*out = new(bool)
		**out = **in
	}
	if in.StoragePerProject != nil {
		in, out := &in.StoragePerProject, &out.StoragePerProject
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemObservation.
func (in *SystemObservation) DeepCopy() *SystemObservation {
	if in == nil {
		return nil
	}
	out := new(SystemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemParameters) DeepCopyInto(out *SystemParameters) {
	*out = *in
	if in.AuditLogForwardEndpoint != nil {
		in, out := &in.AuditLogForwardEndpoint, &out.AuditLogForwardEndpoint
		*out = new(string)
		**out = **in
	}
	if in.BannerMessage != nil {
		in, out := &in.BannerMessage, &out.BannerMessage
		*out = make([]BannerMessageParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationEnable != nil {
		in, out := &in.NotificationEnable, &out.NotificationEnable
		*out = new(bool)
		**out = **in
	}
	if in.ProjectCreationRestriction != nil {
		in, out := &in.ProjectCreationRestriction, &out.ProjectCreationRestriction
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.RobotNamePrefix != nil {
		in, out := &in.RobotNamePrefix, &out.RobotNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.RobotTokenExpiration != nil {
		in, out := &in.RobotTokenExpiration, &out.RobotTokenExpiration
		*out = new(float64)
		**out = **in
	}
	if in.ScannerSkipUpdatePulltime != nil {
		in, out := &in.ScannerSkipUpdatePulltime, &out.ScannerSkipUpdatePulltime
		*out = new(bool)
		**out = **in
	}
	if in.SkipAuditLogDatabase != nil {
		in, out := &in.SkipAuditLogDatabase, &out.SkipAuditLogDatabase
		*out = new(bool)
		**out = **in
	}
	if in.StoragePerProject != nil {
		in, out := &in.StoragePerProject, &out.StoragePerProject
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemParameters.
func (in *SystemParameters) DeepCopy() *SystemParameters {
	if in == nil {
		return nil
	}
	out := new(SystemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemSpec) DeepCopyInto(out *SystemSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemSpec.
func (in *SystemSpec) DeepCopy() *SystemSpec {
	if in == nil {
		return nil
	}
	out := new(SystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemStatus) DeepCopyInto(out *SystemStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemStatus.
func (in *SystemStatus) DeepCopy() *SystemStatus {
	if in == nil {
		return nil
	}
	out := new(SystemStatus)
	in.DeepCopyInto(out)
	return out
}
