// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SecurityInitParameters struct {

	// 123", "CVE-145"] or ["CVE-123"]
	CveAllowlist []*string `json:"cveAllowlist,omitempty" tf:"cve_allowlist,omitempty"`

	// (Number) The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it's not set the CVE allowlist does not expire.
	ExpiresAt *int64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`
}

type SecurityObservation struct {

	// (String) Time of creation of the list.
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// 123", "CVE-145"] or ["CVE-123"]
	CveAllowlist []*string `json:"cveAllowlist,omitempty" tf:"cve_allowlist,omitempty"`

	// (Number) The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it's not set the CVE allowlist does not expire.
	ExpiresAt *int64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Time of update of the list.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type SecurityParameters struct {

	// 123", "CVE-145"] or ["CVE-123"]
	// +kubebuilder:validation:Optional
	CveAllowlist []*string `json:"cveAllowlist,omitempty" tf:"cve_allowlist,omitempty"`

	// (Number) The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it's not set the CVE allowlist does not expire.
	// +kubebuilder:validation:Optional
	ExpiresAt *int64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`
}

// SecuritySpec defines the desired state of Security
type SecuritySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecurityParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityInitParameters `json:"initProvider,omitempty"`
}

// SecurityStatus defines the observed state of Security.
type SecurityStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Security is the Schema for the Securitys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harbor}
type Security struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cveAllowlist) || (has(self.initProvider) && has(self.initProvider.cveAllowlist))",message="spec.forProvider.cveAllowlist is a required parameter"
	Spec   SecuritySpec   `json:"spec"`
	Status SecurityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityList contains a list of Securitys
type SecurityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Security `json:"items"`
}

// Repository type metadata.
var (
	Security_Kind             = "Security"
	Security_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Security_Kind}.String()
	Security_KindAPIVersion   = Security_Kind + "." + CRDGroupVersion.String()
	Security_GroupVersionKind = CRDGroupVersion.WithKind(Security_Kind)
)

func init() {
	SchemeBuilder.Register(&Security{}, &SecurityList{})
}
