//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInitParameters) DeepCopyInto(out *PolicyInitParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.ScopeRef != nil {
		in, out := &in.ScopeRef, &out.ScopeRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScopeSelector != nil {
		in, out := &in.ScopeSelector, &out.ScopeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInitParameters.
func (in *PolicyInitParameters) DeepCopy() *PolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyList.
func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObservation) DeepCopyInto(out *PolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObservation.
func (in *PolicyObservation) DeepCopy() *PolicyObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyParameters) DeepCopyInto(out *PolicyParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.ScopeRef != nil {
		in, out := &in.ScopeRef, &out.ScopeRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScopeSelector != nil {
		in, out := &in.ScopeSelector, &out.ScopeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyParameters.
func (in *PolicyParameters) DeepCopy() *PolicyParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleInitParameters) DeepCopyInto(out *RuleInitParameters) {
	*out = *in
	if in.AlwaysRetain != nil {
		in, out := &in.AlwaysRetain, &out.AlwaysRetain
		*out = new(bool)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MostRecentlyPulled != nil {
		in, out := &in.MostRecentlyPulled, &out.MostRecentlyPulled
		*out = new(int64)
		**out = **in
	}
	if in.MostRecentlyPushed != nil {
		in, out := &in.MostRecentlyPushed, &out.MostRecentlyPushed
		*out = new(int64)
		**out = **in
	}
	if in.NDaysSinceLastPull != nil {
		in, out := &in.NDaysSinceLastPull, &out.NDaysSinceLastPull
		*out = new(int64)
		**out = **in
	}
	if in.NDaysSinceLastPush != nil {
		in, out := &in.NDaysSinceLastPush, &out.NDaysSinceLastPush
		*out = new(int64)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
	if in.UntaggedArtifacts != nil {
		in, out := &in.UntaggedArtifacts, &out.UntaggedArtifacts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleInitParameters.
func (in *RuleInitParameters) DeepCopy() *RuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleObservation) DeepCopyInto(out *RuleObservation) {
	*out = *in
	if in.AlwaysRetain != nil {
		in, out := &in.AlwaysRetain, &out.AlwaysRetain
		*out = new(bool)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MostRecentlyPulled != nil {
		in, out := &in.MostRecentlyPulled, &out.MostRecentlyPulled
		*out = new(int64)
		**out = **in
	}
	if in.MostRecentlyPushed != nil {
		in, out := &in.MostRecentlyPushed, &out.MostRecentlyPushed
		*out = new(int64)
		**out = **in
	}
	if in.NDaysSinceLastPull != nil {
		in, out := &in.NDaysSinceLastPull, &out.NDaysSinceLastPull
		*out = new(int64)
		**out = **in
	}
	if in.NDaysSinceLastPush != nil {
		in, out := &in.NDaysSinceLastPush, &out.NDaysSinceLastPush
		*out = new(int64)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
	if in.UntaggedArtifacts != nil {
		in, out := &in.UntaggedArtifacts, &out.UntaggedArtifacts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleObservation.
func (in *RuleObservation) DeepCopy() *RuleObservation {
	if in == nil {
		return nil
	}
	out := new(RuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleParameters) DeepCopyInto(out *RuleParameters) {
	*out = *in
	if in.AlwaysRetain != nil {
		in, out := &in.AlwaysRetain, &out.AlwaysRetain
		*out = new(bool)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MostRecentlyPulled != nil {
		in, out := &in.MostRecentlyPulled, &out.MostRecentlyPulled
		*out = new(int64)
		**out = **in
	}
	if in.MostRecentlyPushed != nil {
		in, out := &in.MostRecentlyPushed, &out.MostRecentlyPushed
		*out = new(int64)
		**out = **in
	}
	if in.NDaysSinceLastPull != nil {
		in, out := &in.NDaysSinceLastPull, &out.NDaysSinceLastPull
		*out = new(int64)
		**out = **in
	}
	if in.NDaysSinceLastPush != nil {
		in, out := &in.NDaysSinceLastPush, &out.NDaysSinceLastPush
		*out = new(int64)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
	if in.UntaggedArtifacts != nil {
		in, out := &in.UntaggedArtifacts, &out.UntaggedArtifacts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleParameters.
func (in *RuleParameters) DeepCopy() *RuleParameters {
	if in == nil {
		return nil
	}
	out := new(RuleParameters)
	in.DeepCopyInto(out)
	return out
}
