// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ServicesInitParameters struct {

	// (String) Sets the default interrogation service "Clair"
	DefaultScanner *string `json:"defaultScanner,omitempty" tf:"default_scanner,omitempty"`

	// (String) The frequency of the vulnerability scanning is done. This can be Daily, Weekly, Monthly or can be a custom cron string.
	VulnerabilityScanPolicy *string `json:"vulnerabilityScanPolicy,omitempty" tf:"vulnerability_scan_policy,omitempty"`
}

type ServicesObservation struct {

	// (String) Sets the default interrogation service "Clair"
	DefaultScanner *string `json:"defaultScanner,omitempty" tf:"default_scanner,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The frequency of the vulnerability scanning is done. This can be Daily, Weekly, Monthly or can be a custom cron string.
	VulnerabilityScanPolicy *string `json:"vulnerabilityScanPolicy,omitempty" tf:"vulnerability_scan_policy,omitempty"`
}

type ServicesParameters struct {

	// (String) Sets the default interrogation service "Clair"
	// +kubebuilder:validation:Optional
	DefaultScanner *string `json:"defaultScanner,omitempty" tf:"default_scanner,omitempty"`

	// (String) The frequency of the vulnerability scanning is done. This can be Daily, Weekly, Monthly or can be a custom cron string.
	// +kubebuilder:validation:Optional
	VulnerabilityScanPolicy *string `json:"vulnerabilityScanPolicy,omitempty" tf:"vulnerability_scan_policy,omitempty"`
}

// ServicesSpec defines the desired state of Services
type ServicesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServicesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServicesInitParameters `json:"initProvider,omitempty"`
}

// ServicesStatus defines the observed state of Services.
type ServicesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServicesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Services is the Schema for the Servicess API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harbor}
type Services struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vulnerabilityScanPolicy) || (has(self.initProvider) && has(self.initProvider.vulnerabilityScanPolicy))",message="spec.forProvider.vulnerabilityScanPolicy is a required parameter"
	Spec   ServicesSpec   `json:"spec"`
	Status ServicesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServicesList contains a list of Servicess
type ServicesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Services `json:"items"`
}

// Repository type metadata.
var (
	Services_Kind             = "Services"
	Services_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Services_Kind}.String()
	Services_KindAPIVersion   = Services_Kind + "." + CRDGroupVersion.String()
	Services_GroupVersionKind = CRDGroupVersion.WithKind(Services_Kind)
)

func init() {
	SchemeBuilder.Register(&Services{}, &ServicesList{})
}
