// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Replication.
func (mg *Replication) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromIntPtrValue(mg.Spec.ForProvider.RegistryID),
		Extract:      resource.ExtractParamPath("registry_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RegistryIDRef,
		Selector:     mg.Spec.ForProvider.RegistryIDSelector,
		To: reference.To{
			List:    &RegistryList{},
			Managed: &Registry{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RegistryID")
	}
	mg.Spec.ForProvider.RegistryID = reference.ToIntPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RegistryIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromIntPtrValue(mg.Spec.InitProvider.RegistryID),
		Extract:      resource.ExtractParamPath("registry_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RegistryIDRef,
		Selector:     mg.Spec.InitProvider.RegistryIDSelector,
		To: reference.To{
			List:    &RegistryList{},
			Managed: &Registry{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RegistryID")
	}
	mg.Spec.InitProvider.RegistryID = reference.ToIntPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RegistryIDRef = rsp.ResolvedReference

	return nil
}
