// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TasksInitParameters struct {

	// (String) The frequency of the vulnerability scanning is done. Can be to "hourly", "daily" or "weekly"
	VulnerabilityScanPolicy *string `json:"vulnerabilityScanPolicy,omitempty" tf:"vulnerability_scan_policy,omitempty"`
}

type TasksObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The frequency of the vulnerability scanning is done. Can be to "hourly", "daily" or "weekly"
	VulnerabilityScanPolicy *string `json:"vulnerabilityScanPolicy,omitempty" tf:"vulnerability_scan_policy,omitempty"`
}

type TasksParameters struct {

	// (String) The frequency of the vulnerability scanning is done. Can be to "hourly", "daily" or "weekly"
	// +kubebuilder:validation:Optional
	VulnerabilityScanPolicy *string `json:"vulnerabilityScanPolicy,omitempty" tf:"vulnerability_scan_policy,omitempty"`
}

// TasksSpec defines the desired state of Tasks
type TasksSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TasksParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TasksInitParameters `json:"initProvider,omitempty"`
}

// TasksStatus defines the observed state of Tasks.
type TasksStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TasksObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Tasks is the Schema for the Taskss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type Tasks struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vulnerabilityScanPolicy) || (has(self.initProvider) && has(self.initProvider.vulnerabilityScanPolicy))",message="spec.forProvider.vulnerabilityScanPolicy is a required parameter"
	Spec   TasksSpec   `json:"spec"`
	Status TasksStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TasksList contains a list of Taskss
type TasksList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Tasks `json:"items"`
}

// Repository type metadata.
var (
	Tasks_Kind             = "Tasks"
	Tasks_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Tasks_Kind}.String()
	Tasks_KindAPIVersion   = Tasks_Kind + "." + CRDGroupVersion.String()
	Tasks_GroupVersionKind = CRDGroupVersion.WithKind(Tasks_Kind)
)

func init() {
	SchemeBuilder.Register(&Tasks{}, &TasksList{})
}
