// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CollectionInitParameters struct {

	// (Boolean) Allow garbage collection on untagged artifacts.
	DeleteUntagged *bool `json:"deleteUntagged,omitempty" tf:"delete_untagged,omitempty"`

	// (String) Sets the schedule how often the Garbage Collection will run.  Can be to "hourly", "daily", "weekly" or can be a custom cron string ie, "0 5 4 * * *"
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (Number) Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
	Workers *int64 `json:"workers,omitempty" tf:"workers,omitempty"`
}

type CollectionObservation struct {

	// (Boolean) Allow garbage collection on untagged artifacts.
	DeleteUntagged *bool `json:"deleteUntagged,omitempty" tf:"delete_untagged,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Sets the schedule how often the Garbage Collection will run.  Can be to "hourly", "daily", "weekly" or can be a custom cron string ie, "0 5 4 * * *"
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (Number) Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
	Workers *int64 `json:"workers,omitempty" tf:"workers,omitempty"`
}

type CollectionParameters struct {

	// (Boolean) Allow garbage collection on untagged artifacts.
	// +kubebuilder:validation:Optional
	DeleteUntagged *bool `json:"deleteUntagged,omitempty" tf:"delete_untagged,omitempty"`

	// (String) Sets the schedule how often the Garbage Collection will run.  Can be to "hourly", "daily", "weekly" or can be a custom cron string ie, "0 5 4 * * *"
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (Number) Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
	// +kubebuilder:validation:Optional
	Workers *int64 `json:"workers,omitempty" tf:"workers,omitempty"`
}

// CollectionSpec defines the desired state of Collection
type CollectionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CollectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CollectionInitParameters `json:"initProvider,omitempty"`
}

// CollectionStatus defines the observed state of Collection.
type CollectionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CollectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Collection is the Schema for the Collections API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harbor}
type Collection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schedule) || (has(self.initProvider) && has(self.initProvider.schedule))",message="spec.forProvider.schedule is a required parameter"
	Spec   CollectionSpec   `json:"spec"`
	Status CollectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CollectionList contains a list of Collections
type CollectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Collection `json:"items"`
}

// Repository type metadata.
var (
	Collection_Kind             = "Collection"
	Collection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Collection_Kind}.String()
	Collection_KindAPIVersion   = Collection_Kind + "." + CRDGroupVersion.String()
	Collection_GroupVersionKind = CRDGroupVersion.WithKind(Collection_Kind)
)

func init() {
	SchemeBuilder.Register(&Collection{}, &CollectionList{})
}
