//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRule) DeepCopyInto(out *TagRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRule.
func (in *TagRule) DeepCopy() *TagRule {
	if in == nil {
		return nil
	}
	out := new(TagRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRuleInitParameters) DeepCopyInto(out *TagRuleInitParameters) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRuleInitParameters.
func (in *TagRuleInitParameters) DeepCopy() *TagRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(TagRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRuleList) DeepCopyInto(out *TagRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TagRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRuleList.
func (in *TagRuleList) DeepCopy() *TagRuleList {
	if in == nil {
		return nil
	}
	out := new(TagRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRuleObservation) DeepCopyInto(out *TagRuleObservation) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRuleObservation.
func (in *TagRuleObservation) DeepCopy() *TagRuleObservation {
	if in == nil {
		return nil
	}
	out := new(TagRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRuleParameters) DeepCopyInto(out *TagRuleParameters) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRuleParameters.
func (in *TagRuleParameters) DeepCopy() *TagRuleParameters {
	if in == nil {
		return nil
	}
	out := new(TagRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRuleSpec) DeepCopyInto(out *TagRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRuleSpec.
func (in *TagRuleSpec) DeepCopy() *TagRuleSpec {
	if in == nil {
		return nil
	}
	out := new(TagRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRuleStatus) DeepCopyInto(out *TagRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRuleStatus.
func (in *TagRuleStatus) DeepCopy() *TagRuleStatus {
	if in == nil {
		return nil
	}
	out := new(TagRuleStatus)
	in.DeepCopyInto(out)
	return out
}
