// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TagRuleInitParameters struct {

	// (Boolean) Specify if the rule is disable or not. Defaults to false
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The project id of which you would like to apply this policy.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) For the repositories excluding.
	RepoExcluding *string `json:"repoExcluding,omitempty" tf:"repo_excluding,omitempty"`

	// (String) For the repositories matching.
	RepoMatching *string `json:"repoMatching,omitempty" tf:"repo_matching,omitempty"`

	// (String) For the tag excluding.
	TagExcluding *string `json:"tagExcluding,omitempty" tf:"tag_excluding,omitempty"`

	// (String) For the tag matching.
	TagMatching *string `json:"tagMatching,omitempty" tf:"tag_matching,omitempty"`
}

type TagRuleObservation struct {

	// (Boolean) Specify if the rule is disable or not. Defaults to false
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The project id of which you would like to apply this policy.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) For the repositories excluding.
	RepoExcluding *string `json:"repoExcluding,omitempty" tf:"repo_excluding,omitempty"`

	// (String) For the repositories matching.
	RepoMatching *string `json:"repoMatching,omitempty" tf:"repo_matching,omitempty"`

	// (String) For the tag excluding.
	TagExcluding *string `json:"tagExcluding,omitempty" tf:"tag_excluding,omitempty"`

	// (String) For the tag matching.
	TagMatching *string `json:"tagMatching,omitempty" tf:"tag_matching,omitempty"`
}

type TagRuleParameters struct {

	// (Boolean) Specify if the rule is disable or not. Defaults to false
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The project id of which you would like to apply this policy.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) For the repositories excluding.
	// +kubebuilder:validation:Optional
	RepoExcluding *string `json:"repoExcluding,omitempty" tf:"repo_excluding,omitempty"`

	// (String) For the repositories matching.
	// +kubebuilder:validation:Optional
	RepoMatching *string `json:"repoMatching,omitempty" tf:"repo_matching,omitempty"`

	// (String) For the tag excluding.
	// +kubebuilder:validation:Optional
	TagExcluding *string `json:"tagExcluding,omitempty" tf:"tag_excluding,omitempty"`

	// (String) For the tag matching.
	// +kubebuilder:validation:Optional
	TagMatching *string `json:"tagMatching,omitempty" tf:"tag_matching,omitempty"`
}

// TagRuleSpec defines the desired state of TagRule
type TagRuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TagRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TagRuleInitParameters `json:"initProvider,omitempty"`
}

// TagRuleStatus defines the observed state of TagRule.
type TagRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TagRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TagRule is the Schema for the TagRules API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harbor}
type TagRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   TagRuleSpec   `json:"spec"`
	Status TagRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TagRuleList contains a list of TagRules
type TagRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TagRule `json:"items"`
}

// Repository type metadata.
var (
	TagRule_Kind             = "TagRule"
	TagRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TagRule_Kind}.String()
	TagRule_KindAPIVersion   = TagRule_Kind + "." + CRDGroupVersion.String()
	TagRule_GroupVersionKind = CRDGroupVersion.WithKind(TagRule_Kind)
)

func init() {
	SchemeBuilder.Register(&TagRule{}, &TagRuleList{})
}
