apiVersion: robot.harbor.m.crossplane.io/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: robot/v1alpha1/account
  labels:
    testing.upbound.io/example-name: system
  name: system
  namespace: crossplane-system
spec:
  forProvider:
    description: system level robot account
    level: system
    name: example-system
    permissions:
    - access:
      - action: create
        resource: label
      kind: system
      namespaceSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    - access:
      - action: push
        resource: repository
      kind: project
      namespaceSelector:
        matchLabels:
          testing.upbound.io/example-name: main
    - access:
      - action: pull
        resource: repository
      kind: project
      namespaceSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    secretSecretRef:
      key: attribute.password.result
      name: example-

---

apiVersion: harbor.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: robot/v1alpha1/account
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: crossplane-system
spec:
  forProvider: {}
